### ISSUE TITLE
add the files to the files dictionary

### ISSUE THREAD

**Issue by ianstormtaylor** [thehydroimpulse/metalsmith-static#1]
a slight improvement, if you want the files in the static directory to be parsed by the later metalsmith plugins (imagine like compressing images or something) then instead of copying the files directly you'll want to add them to the `files` object that is passed into the plugin

you can check out how the core library reads the source files initially [here](https://github.com/segmentio/metalsmith/blob/master/lib/index.js#L126-L150) for an example

let me know if that doesn't make sense!

**Comment by thehydroimpulse** [comment]
@ianstormtaylor Oh awesome. That definitely seems better.

**Comment by blvz** [comment]
I've migrated **from** [metalsmith-assets](http://github.com/treygriffith/metalsmith-assets) specifically because of this.

I'm using [metalsmith-watch](http://github.com/FWeinb/metalsmith-watch) with `{livereload: {liveCSS: true}}`, so when I save my CSS file, the browser gets updated styles without losing current DOM state. `metalsmith-watch` watches files for changes, triggers `metalsmith.run` for that single changed file and reports the transformed `files` object to livereload.

But when static files are added to the `files` object, they all get reported back to `metalsmith-watch`, which in turn reports them to livereload, resulting in a CSS refresh, followed by a full page refresh.

I just thought you guys would like to know. :D

**Comment by thehydroimpulse** [comment]
@blvz Thanks for the heads up! I'm currently not using this library nor metalsmith which is why this library is stale.
